env:
  global:
  - CC_TEST_REPORTER_ID=2c651b17919b6d64b8a199f1320273cb8cd0af60bd259a3675b835726b5c79dc
language: node_js
node_js:
- '12'
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
script:
- npm run test:coverage
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
notifications:
  email: false
deploy:
  provider: npm
  email: shawn@wmsi.co
  skip_clean: true
  api_key: $NPM_TOKEN
  on:
    tags: true
    repo: BadOPCode/log-skidder
