parcelRequire=function(e,r,t,n){var i,o="function"==typeof parcelRequire&&parcelRequire,u="function"==typeof require&&require;function f(t,n){if(!r[t]){if(!e[t]){var i="function"==typeof parcelRequire&&parcelRequire;if(!n&&i)return i(t,!0);if(o)return o(t,!0);if(u&&"string"==typeof t)return u(t);var c=new Error("Cannot find module '"+t+"'");throw c.code="MODULE_NOT_FOUND",c}p.resolve=function(r){return e[t][1][r]||r},p.cache={};var l=r[t]=new f.Module(t);e[t][0].call(l.exports,p,l,l.exports,this)}return r[t].exports;function p(e){return f(p.resolve(e))}}f.isParcelRequire=!0,f.Module=function(e){this.id=e,this.bundle=f,this.exports={}},f.modules=e,f.cache=r,f.parent=o,f.register=function(r,t){e[r]=[function(e,r){r.exports=t},{}]};for(var c=0;c<t.length;c++)try{f(t[c])}catch(e){i||(i=e)}if(t.length){var l=f(t[t.length-1]);"object"==typeof exports&&"undefined"!=typeof module?module.exports=l:"function"==typeof define&&define.amd?define(function(){return l}):n&&(this[n]=l)}if(parcelRequire=f,i)throw i;return f}({"VY3w":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0});var e=function(){return function(e,a){var r=this;this.error=function(){for(var e=[],a=0;a<arguments.length;a++)e[a]=arguments[a];r._handlers.process({appName:r._appName,eventType:"error",data:e})},this.log=function(){for(var e=[],a=0;a<arguments.length;a++)e[a]=arguments[a];r._handlers.process({appName:r._appName,eventType:"log",data:e})},this.warn=function(){for(var e=[],a=0;a<arguments.length;a++)e[a]=arguments[a];r._handlers.process({appName:r._appName,eventType:"warn",data:e})},this.list=function(e){var a={appName:r._appName};return e&&(a.eventType=e),r._handlers.search(a)},this._appName=e,this._handlers=a}}();exports.LogManager=e;
},{}],"uAAW":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0});var e=function(){function e(){var e=this;this._handlers=[],this._eventStack=[],this.addHandler=function(t){e._handlers.push(t)},this.process=function(t){e._eventStack.push(t),e._handlers.forEach(function(e){e(t)})},this.search=function(t){return e._eventStack.filter(function(e){return(!t.appName||e.appName===t.appName)&&(!t.eventType||e.eventType===t.eventType)})}}return Object.defineProperty(e.prototype,"handlers",{get:function(){return this._handlers},enumerable:!0,configurable:!0}),e}();exports.LogHandler=e;
},{}],"ss5T":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0});var e=require("./LogManager"),n=require("./LogHandler"),r=function(){function r(){var r=this;this.handlers=new n.LogHandler,this._managers={undefined:new e.LogManager("undefined",this.handlers)},this.errorConsoleHandler=function(){for(var e,n=[],o=0;o<arguments.length;o++)n[o]=arguments[o];(e=r.Manager("undefined")).error.apply(e,n)},this.logConsoleHandler=function(){for(var e,n=[],o=0;o<arguments.length;o++)n[o]=arguments[o];(e=r.Manager("undefined")).log.apply(e,n)},this.warnConsoleHandler=function(){for(var e,n=[],o=0;o<arguments.length;o++)n[o]=arguments[o];(e=r.Manager("undefined")).warn.apply(e,n)},this._original={error:console.error,log:console.log,warn:console.warn}}return Object.defineProperty(r.prototype,"original",{get:function(){return this._original},enumerable:!0,configurable:!0}),r.prototype.hookConsoleMethods=function(){console.error=this.errorConsoleHandler,console.log=this.logConsoleHandler,console.warn=this.warnConsoleHandler},r.prototype.Manager=function(e){return this._managers[e]||this._managers.undefined},r.prototype.Attach=function(n){return this._managers[n]=new e.LogManager(n,this.handlers),this._managers[n]},r}();exports.LogSkidder=r;
},{"./LogManager":"VY3w","./LogHandler":"uAAW"}],"QCba":[function(require,module,exports) {
"use strict";function o(e){return(o="function"==typeof Symbol&&"symbol"==typeof Symbol.iterator?function(o){return typeof o}:function(o){return o&&"function"==typeof Symbol&&o.constructor===Symbol&&o!==Symbol.prototype?"symbol":typeof o})(e)}Object.defineProperty(exports,"__esModule",{value:!0});var e,t=require("./LogSkidder"),d="object"!==("undefined"==typeof window?"undefined":o(window));d?e=new t.LogSkidder:(window.LogSkidder||(window.LogSkidder=new t.LogSkidder,window.LogSkidder.hookConsoleMethods()),e=window.LogSkidder),exports.default=e;
},{"./LogSkidder":"ss5T"}]},{},["QCba"], null)
//# sourceMappingURL=/index.js.map